=== PennyLaneAI/demos/metadata_schemas/demo.metadata.schema.0.1.10.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.9.json",
    "title": "Demo Metadata",
    "description": "A demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "slug": {
        "description": "The slug of the demo. This should match the base name of the metadata file.",
        "type": "string",
        "minLength": 1
      },
      "executable_stable":{
        "description": "Whether or not the master branch version of this demo is executable.",
        "type": "boolean"
      },
      "executable_latest":{
        "description": "Whether or not the dev branch version of this demo is executable.",
        "type": "boolean"
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.2.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware",
            "How-to",
            "Compilation",
            "Resource Estimation",
            "FTQC"
          ]
        },
        "minItems": 1
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      },
      "hardware": {
        "description": "An array of objects representing third-party vendors who can run the demo on their hardware. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/hardware.schema.0.1.0.json"
        }
      },
      "discussionForumUrl": {
        "description": "Link to dedicated discussion forum thread on https://discuss.pennylane.ai/ for this demo",
        "type": "string",
        "format": "uri",
        "pattern": "(^https?:\/\/(www.)?discuss.pennylane.ai(?:\/.*)?$)"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/demos/demonstrations_v2/tutorial_odegen/metadata.json
{
    "title": "Evaluating analytic gradients of pulse programs on quantum computers",
    "authors": [
        {
            "username": "Qottmann"
        }
    ],
    "executable_stable": false,
    "executable_latest": false,
    "dateOfPublication": "2023-12-12T00:00:00+00:00",
    "dateOfLastModification": "2026-06-01T15:48:14+00:00",
    "categories": [
        "Optimization",
        "Quantum Computing",
        "Quantum Hardware"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/odegen/thumbnail_odegen.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_odegen.png"
        }
    ],
    "seoDescription": "Learn how to compute analytic gradients of pulse programs on quantum hardware",
    "doi": "",
    "references": [
        {
            "id": "Kottmann",
            "type": "preprint",
            "title": "Evaluating analytic gradients of pulse programs on quantum computers",
            "authors": "Korbinian Kottmann, Nathan Killoran",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2309.16756",
            "url": "https://arxiv.org/abs/2309.16756"
        },
        {
            "id": "Krantz",
            "type": "article",
            "title": "Philip Krantz, Morten Kjaergaard, Fei Yan, Terry P. Orlando, Simon Gustavsson, William D. Oliver",
            "authors": "A Quantum Engineer's Guide to Superconducting Qubits",
            "year": "2019",
            "publisher": "",
            "journal": "J. Magn. Reson. 172, 296-305",
            "doi": "10.1063/1.5089550",
            "url": "https://arxiv.org/abs/1904.06560"
        },
        {
            "id": "Mitei",
            "type": "preprint",
            "title": "Gate-free state preparation for fast variational quantum eigensolver simulations: ctrl-VQE",
            "authors": "Oinam Romesh Meitei, Bryan T. Gard, George S. Barron, David P. Pappas, Sophia E. Economou, Edwin Barnes, Nicholas J. Mayhall",
            "year": "2020",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2008.04302",
            "url": "https://arxiv.org/abs/2008.04302"
        },
        {
            "id": "Banchi",
            "type": "article",
            "title": "Measuring Analytic Gradients of General Quantum Evolution with the Stochastic Parameter Shift Rule",
            "authors": "Leonardo Banchi, Gavin E. Crooks",
            "year": "2020",
            "publisher": "",
            "journal": "Quantum",
            "doi": "10.22331/q-2021-01-25-386",
            "url": "https://arxiv.org/abs/2005.10299",
            "preprint": "https://arxiv.org/abs/2005.10299"
        },
        {
            "id": "Leng",
            "type": "preprint",
            "title": "Differentiable Analog Quantum Computing for Optimization and Control",
            "authors": "Jiaqi Leng, Yuxiang Peng, Yi-Ling Qiao, Ming Lin, Xiaodi Wu",
            "year": "2022",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2210.15812",
            "url": "https://arxiv.org/abs/2210.15812",
            "preprint": "https://arxiv.org/abs/2210.15812"
        },
        {
            "id": "Patterson",
            "type": "preprint",
            "title": "Calibration of the cross-resonance two-qubit gate between directly-coupled transmons",
            "authors": "A. D. Patterson, J. Rahamim, T. Tsunoda, P. Spring, S. Jebari, K. Ratter, M. Mergenthaler, G. Tancredi, B. Vlastakis, M. Esposito, P. J. Leek",
            "year": "2019",
            "publisher": "",
            "journal": "Phys. Rev. Applied 12, 064013",
            "doi": "10.1103/PhysRevApplied.12.064013",
            "url": "https://doi.org/10.1103/PhysRevApplied.12.064013",
            "preprint": "https://arxiv.org/abs/1905.05670"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_pulse_programming101",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "oqc_pulse",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "ahs_aquila",
            "weight": 0.5
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_QUBO/metadata.json
{
    "title": "Quadratic unconstrained binary optimization",
    "authors": [
        {
            "username": "alejomonbar"
        }
    ],
    "executable_stable": false,
    "executable_latest": false,
    "dateOfPublication": "2024-02-29T00:00:00+00:00",
    "dateOfLastModification": "2026-10-19T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demonstration_assets/QUBO/thumbnail_QUBO_2024-02-06.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_QuBO_2024-02-06.png"
        }
    ],
    "seoDescription": "Learn how to solve a QUBO problem in a quantum computer.",
    "doi": "",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [],
    "discussionForumUrl": "https://discuss.pennylane.ai/t/quadratic-unconstrained-binary-optimization-qubo-demo/7339"
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_vqe_qng/metadata.json
{
    "title": "Accelerating VQEs with quantum natural gradient",
    "authors": [
        {
            "username": "mli"
        },
        {
            "username": "lbozanic"
        },
        {
            "username": "ssim"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2020-11-06T00:00:00+00:00",
    "dateOfLastModification": "2026-05-28T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_accelerating_VQEs.png"
        }
    ],
    "seoDescription": "Accelerating variational quantum eigensolvers using quantum natural gradients in PennyLane.",
    "doi": "",
    "references": [
        {
            "id": "stokes2019",
            "type": "article",
            "title": "Quantum Natural Gradient",
            "authors": "Stokes, James, et al.",
            "year": "2019",
            "journal": "",
            "url": "https://arxiv.org/abs/1909.02108"
        },
        {
            "id": "yamamoto2019",
            "type": "article",
            "title": "On the natural gradient for variational quantum eigensolver",
            "authors": "Yamamoto, Naoki",
            "year": "2019",
            "journal": "",
            "url": "https://arxiv.org/abs/1909.05074"
        },
        {
            "id": "peruzzo2014",
            "type": "article",
            "title": "A variational eigenvalue solver on a photonic quantum processor",
            "authors": "Alberto Peruzzo, Jarrod McClean et al.",
            "year": "2014",
            "journal": "Nature Communications",
            "url": "https://www.nature.com/articles/ncomms5213?origin=ppub"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqe",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_quantum_natural_gradient",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_vqls/metadata.json
{
    "title": "Variational quantum linear solver",
    "authors": [
        {
            "username": "amari"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2019-11-04T00:00:00+00:00",
    "dateOfLastModification": "2026-10-19T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_variationally_quantum_linear_solver.png"
        }
    ],
    "seoDescription": "Implementing the variational quantum linear solver to solve a system of linear equation with a quantum device.",
    "doi": "",
    "references": [
        {
            "id": "BravoPrieto2019",
            "type": "article",
            "title": "Variational Quantum Linear Solver: A Hybrid Algorithm for Linear Systems.",
            "authors": "Carlos Bravo-Prieto, Ryan LaRose, Marco Cerezo, Yigit Subasi, Lukasz Cincio, Patrick J. Coles",
            "year": "2019",
            "journal": "",
            "doi": "10.48550/arXiv.1909.05820",
            "url": "https://arxiv.org/abs/1909.05820"
        }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.1909.05820"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_coherent_vqls",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_coherent_vqls/metadata.json
{
    "title": "Coherent Variational Quantum Linear Solver",
    "authors": [
        {
            "username": "amari"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2019-11-06T00:00:00+00:00",
    "dateOfLastModification": "2026-06-19T00:00:00+00:00",
    "categories": [
        "Optimization"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_coherent_variational_quantum_learner_solver.png"
        }
    ],
    "seoDescription": "This demonstration extends the variational quantum linear solver to solve linear equations defined by a probabilistic coherent operation.",
    "doi": "",
    "references": [
        {
            "id": "BravoPrieto2019",
            "type": "article",
            "title": "Variational Quantum Linear Solver: A Hybrid Algorithm for Linear Systems",
            "authors": "Carlos Bravo-Prieto, Ryan LaRose, Marco Cerezo, Yigit Subasi, Lukasz Cincio, Patrick J. Coles",
            "year": "2019",
            "journal": "",
            "url": "https://arxiv.org/abs/1909.05820"
        },
        {
            "id": "Kothari2014",
            "type": "phdthesis",
            "title": "Efficient algorithms in quantum query complexity",
            "authors": "Robin Kothari",
            "year": "2014",
            "journal": "",
            "url": ""
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_vqls",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_active_volume/metadata.json
{
    "title": "Active volume",
    "authors": [
        {
            "username": "david"
        },
        {
            "username": "dwierichs"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2026-01-21T10:00:00+00:00",
    "dateOfLastModification": "2026-07-14T12:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Compilation"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/pennylane-demo-active-volume-thumbnail.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/pennylane-demo-active-volume-large-thumbnail.png"
        }
    ],
    "seoDescription": "Learn about active volume and how to compile for an active volume quantum computer.",
    "doi": "",
    "references": [
        {
            "id": "Litinski2022",
            "type": "article",
            "title": "Active volume: An architecture for efficient fault-tolerant quantum computers with limited non-local connections",
            "authors": "Daniel Litinski, Naomi Nickerson",
            "year": "2022",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/2211.15465"
        },
        {
        "id": "Litinski2018",
        "type": "article",
        "title": "A Game of Surface Codes: Large-Scale Quantum Computing with Lattice Surgery",
        "authors": "Daniel Litinski",
        "year": "2018",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/1808.02892v3"
    },
    {
        "id": "Gidney2018",
        "type": "article",
        "title": "Halving the cost of quantum addition",
        "authors": "Craig Gidney",
        "year": "2018",
        "journal": "Quantum",
        "url": "https://quantum-journal.org/papers/q-2018-06-18-74/"
    },
    {
        "id": "PauliFrame",
        "type": "article",
        "title": "Pauli Frames for Quantum Computer Architectures",
        "authors": "L. Riesebos, X. Fu, S. Varsamopoulos, C. G. Almudever, K. Bertels",
        "year": "2017",
        "journal": "Proceedings of the 54th Annual Design Automation Conference (DAC '17)",
        "url": "https://doi.org/10.1145/3061639.3062300"
    }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.2211.15465"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_lattice_surgery",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_game_of_surface_codes",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_zx_calculus",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_game_of_surface_codes/metadata.json
{
    "title": "A game of surface codes: Large-scale quantum computing with lattice surgery",
    "authors": [
        {
            "username": "Qottmann"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2025-06-02T00:00:00+00:00",
    "dateOfLastModification": "2026-10-19T00:00:00+00:00",
    "categories": [
        "Quantum Computing",
        "Compilation",
        "Algorithms",
        "FTQC"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_game_of_surface_codes.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_game_of_surface_codes.png"
        }
    ],
    "seoDescription": "A game of surface codes: Exploring space-time tradeoffs in surface code based quantum computation.",
    "doi": "",
    "references": [
        {
            "id": "Litinski",
            "type": "preprint",
            "title": "A Game of Surface Codes: Large-Scale Quantum Computing with Lattice Surgery",
            "authors": "Daniel Litinski",
            "year": "2021",
            "publisher": "",
            "journal": "",
            "doi": "10.22331/q-2019-03-05-128",
            "url": "https://arxiv.org/abs/1808.02892"
        }
    ],
    "basedOnPapers": [
        "10.22331/q-2019-03-05-128"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_toric_code",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mbqc",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/qrack/metadata.json
{
    "title": "QJIT compilation with Qrack and Catalyst",
    "authors": [
        {
            "username": "dstrano"
        }
    ],
    "executable_stable": false,
    "executable_latest": true,
    "dateOfPublication": "2024-07-10T00:00:00+00:00",
    "dateOfLastModification": "2026-05-25T00:00:00+00:00",
    "categories": [
        "Compilation",
        "Devices and Performance"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_qrack_catalyst_integration.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_qrack_catalyst_integration.png"
        }
    ],
    "seoDescription": "Quantum JIT compilation (QJIT) using the Qrack device for PennyLane and Catalyst, with GPU-acceleration and novel optimization.",
    "doi": "",
    "references": [
        {
            "id": "QECReport",
            "type": "preprint",
            "title": "Exact and approximate simulation of large quantum circuits on a single GPU",
            "authors": "Daniel Strano, Benn Bollay, Aryan Blaauw, Nathan Shammah, William J. Zeng, Andrea Mari",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2304.14969",
            "url": "https://arxiv.org/abs/2304.14969"
        },
        {
            "id": "Wille",
            "type": "preprint",
            "title": "Decision Diagrams for Quantum Computing",
            "authors": "Robert Wille, Stefan Hillmich, Lukas Burgholzer",
            "year": "2023",
            "publisher": "",
            "journal": "",
            "doi": "10.48550/arXiv.2302.04687",
            "url": "https://arxiv.org/abs/2302.04687"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qft",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_clifford_circuit_simulations",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mcm_introduction",
            "weight": 1.0
        }
    ]
}
