=== PennyLaneAI/demos/metadata_schemas/demo.metadata.schema.0.1.10.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "demo.metadata.schema.0.1.9.json",
    "title": "Demo Metadata",
    "description": "A demo's metadata",
    "type": "object",
    "properties": {
      "title": {
        "description": "The title of the demo.",
        "type": "string",
        "minLength": 2
      },
      "slug": {
        "description": "The slug of the demo. This should match the base name of the metadata file.",
        "type": "string",
        "minLength": 1
      },
      "executable_stable":{
        "description": "Whether or not the master branch version of this demo is executable.",
        "type": "boolean"
      },
      "executable_latest":{
        "description": "Whether or not the dev branch version of this demo is executable.",
        "type": "boolean"
      },
      "authors": {
        "description": "The author(s) of the demo. This array must contain at least one item.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/author.schema.0.2.0.json"
        },
        "minItems": 1
      },
      "dateOfPublication": {
        "description": "The date on which the demo was first published, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "dateOfLastModification": {
        "description": "The date on which the demo was last modified, in the form YYYY-MM-DDTHH:MM:SS+00:00.",
        "type": "string",
        "format": "date-time",
        "minLength": 25,
        "maxLength": 25
      },
      "categories": {
        "description": "An array of the categories that this demo is in.",
        "type": "array",
        "items": {
          "enum": [
            "Algorithms",
            "Getting Started",
            "Optimization",
            "Quantum Machine Learning",
            "Quantum Chemistry",
            "Devices and Performance",
            "Quantum Computing",
            "Quantum Hardware",
            "How-to",
            "Compilation",
            "Resource Estimation",
            "FTQC"
          ]
        },
        "minItems": 1
      },
      "tags": {
        "description": "An array of the tags that the demo has. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "previewImages": {
        "description": "An array of the different images that can be used as previews for this demo - e.g., thumbnails, social media cards (perhaps of different aspect ratios).",
        "type": "array",
        "items": {
          "$ref": "file:./objects/preview.image.schema.0.1.0.json"
        },
        "minItems": 1
      },
      "seoDescription": {
        "description": "A description of the demo suitable for SEO purposes. Ideally this should be less than 150 characters, but this is not a strict limit. It should be a full, grammatically-correct sentence ending in a full stop.",
        "type": "string",
        "minLength": 2
      },
      "doi": {
        "description": "The DOI for the demo.",
        "type": "string",
        "pattern": "^$|^10[.]"
      },
      "references": {
        "description": "An array of the references used for the demo.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/reference.schema.0.1.0.json"
        }
      },
      "basedOnPapers": {
        "description": "An array of the DOIs for the papers the demo is based on. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "referencedByPapers": {
        "description": "An array of the DOIs of any papers that reference the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "relatedContent": {
        "description": "An array of objects describing the content related to the demo. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/related.content.schema.0.1.0.json"
        }
      },
      "hardware": {
        "description": "An array of objects representing third-party vendors who can run the demo on their hardware. An empty array is allowed.",
        "type": "array",
        "items": {
          "$ref": "file:./objects/hardware.schema.0.1.0.json"
        }
      },
      "discussionForumUrl": {
        "description": "Link to dedicated discussion forum thread on https://discuss.pennylane.ai/ for this demo",
        "type": "string",
        "format": "uri",
        "pattern": "(^https?:\/\/(www.)?discuss.pennylane.ai(?:\/.*)?$)"
      }
    },
    "required": [
      "title", "authors", "dateOfPublication", "dateOfLastModification", "categories", "tags", "previewImages", "seoDescription", "doi", "references", "basedOnPapers", "referencedByPapers", "relatedContent"
    ]
  }

=== PennyLaneAI/demos/demonstrations_v2/tutorial_qaoa_intro/metadata.json
{
    "title": "Intro to QAOA",
    "authors": [
        {
            "username": "jceroni"
        }
    ],
    "executable_stable": false,
    "executable_latest": false,
    "dateOfPublication": "2020-11-18T00:00:00+00:00",
    "dateOfLastModification": "2026-10-23T00:00:00+00:00",
    "categories": [
        "Optimization",
        "Getting Started"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_intro_to_QAOA.png"
        }
    ],
    "seoDescription": "Learn how to implement QAOA with PennyLane",
    "doi": "",
    "references": [],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_qaoa_maxcut",
            "weight": 1.0
        }
    ],
    "hardware": [
        {
            "id": "qbraid",
            "link": "https://account.qbraid.com?gitHubUrl=https://github.com/PennyLaneAI/pennylane-demo-notebooks.git",
            "logo": "/_static/hardware_logos/qbraid.png"
        }
    ],
    "discussionForumUrl": "https://discuss.pennylane.ai/t/qaoa-and-optimization/5188"
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_data_reuploading_classifier/metadata.json
{
    "title": "Data-reuploading classifier",
    "authors": [
        {
            "username": "quantshah"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2019-10-11T00:00:00+00:00",
    "dateOfLastModification": "2026-06-19T15:48:14+00:00",
    "categories": [
        "Quantum Machine Learning"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_data-reuploading_classified.png"
        }
    ],
    "seoDescription": "Implement a single-qubit universal quantum classifier using PennyLane.",
    "doi": "",
    "references": [
        {
            "id": "PerezSalinas2019",
            "type": "article",
            "title": "Data re-uploading for a universal quantum classifier",
            "authors": "Pérez-Salinas, Adrián, et al.",
            "year": "2019",
            "journal": "",
            "url": ""
        },
        {
            "id": "Kingma2014",
            "type": "article",
            "title": "Adam: A method for stochastic optimization",
            "authors": "Kingma, Diederik P., and Ba, J.",
            "year": "2014",
            "journal": "",
            "url": ""
        },
        {
            "id": "Liu1989",
            "type": "article",
            "title": "On the limited memory BFGS method for large scale optimization.",
            "authors": "Liu, Dong C., and Nocedal, J.",
            "year": "1989",
            "journal": "Mathematical programming",
            "url": ""
        }
    ],
    "basedOnPapers": [
        "10.48550/arXiv.1907.02085"
    ],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_variational_classifier",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_multiclass_classification",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_expressivity_fourier_series",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_unitary_designs/metadata.json
{
    "title": "Unitary designs",
    "authors": [
        {
            "username": "glassnotes"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2021-09-07T00:00:00+00:00",
    "dateOfLastModification": "2026-05-15T00:00:00+00:00",
    "categories": [
        "Quantum Machine Learning",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_unitary_designs.png"
        }
    ],
    "seoDescription": "Learn about designs and their uses in quantum computing.",
    "doi": "",
    "references": [
        {
            "id": "Handbook",
            "type": "book",
            "title": "Handbook of Combinatorial Designs, Second Edition",
            "authors": "C. J. Colbourn and J. H. Dinitz",
            "year": "2006",
            "publisher": "Chapman & Hall/CRC",
            "url": ""
        },
        {
            "id": "Delsarte",
            "type": "article",
            "title": "Spherical Codes and Designs",
            "authors": "P. Delsarte, J.M. Goethals, J.J. Seidel",
            "year": "1977",
            "journal": "Geometriae Dedicata",
            "url": ""
        },
        {
            "id": "sph4design",
            "type": "article",
            "title": "New spherical 4-designs",
            "authors": "R. H. Hardin and N. J. A. Sloane",
            "year": "1992",
            "journal": "Discrete Mathematics",
            "url": "https://www.sciencedirect.com/science/article/pii/0012365X9290552Q"
        },
        {
            "id": "Ambainis",
            "type": "article",
            "title": "Quantum t-designs: t-wise independence in the quantum world.",
            "authors": "A. Ambainis and J. Emerson",
            "year": "2007",
            "journal": "Twenty-Second Annual IEEE Conference on Computational Complexity",
            "url": "https://arxiv.org/abs/quant-ph/0701126"
        },
        {
            "id": "Klappenecker",
            "type": "article",
            "title": "Mutually unbiased bases, spherical designs, and frames.",
            "authors": "A. Klappenecker and M. Roetteler",
            "year": "2005",
            "journal": "Proceedings of SPIE",
            "volume": "5914",
            "url": ""
        },
        {
            "id": "Dankert",
            "type": "article",
            "title": "Exact and Approximate Unitary 2-Designs: Constructions and Applications.",
            "authors": "C. Dankert, R. Cleve, J. Emerson, and E. Levine",
            "year": "2009",
            "journal": "Phys. Rev. A",
            "url": "https://arxiv.org/abs/quant-ph/0606161"
        },
        {
            "id": "DankertThesis",
            "type": "article",
            "title": "Efficient Simulation of Random Quantum States and Operators.",
            "authors": "C. Dankert",
            "year": "2005",
            "journal": "",
            "url": "https://arxiv.org/abs/quant-ph/0512217"
        },
        {
            "id": "Gross",
            "type": "article",
            "title": "Evenly distributed unitaries: on the structure of unitary designs",
            "authors": "D. Gross, K. Audenaert, and J. Eisert",
            "year": "2007",
            "journal": "J. Math. Phys.",
            "url": "https://arxiv.org/abs/quant-ph/0611002"
        },
        {
            "id": "Roy",
            "type": "article",
            "title": "Unitary designs and codes",
            "authors": "A. Roy and A. J. Scott",
            "year": "2009",
            "journal": "Des. Codes Cryptogr.",
            "url": "https://arxiv.org/abs/0809.3813"
        },
        {
            "id": "Bannai",
            "type": "article",
            "title": "On the explicit constructions of certain unitary t-designs.",
            "authors": "E. Bannai, M. Nakahara, D. Zhao, and Y. Zhu",
            "year": "2019",
            "journal": "J. Phys. A: Math. Theor.",
            "url": "https://arxiv.org/abs/1906.04583"
        },
        {
            "id": "Nakata",
            "type": "article",
            "title": "Quantum circuits for exact unitary t-designs and applications to higher-order randomized benchmarking.",
            "authors": "Y. Nakata et al.",
            "year": "2021",
            "journal": "",
            "url": "https://arxiv.org/abs/2102.12617"
        },
        {
            "id": "PQC",
            "type": "article",
            "title": "Private Quantum Channels",
            "authors": "A. Ambainis, M. Mosca, A. Tapp, and R. de Wolf",
            "year": "2000",
            "journal": "Proc. 41st FOCS",
            "url": "https://homepages.cwi.nl/~rdewolf/publ/qc/AMTW00.pdf"
        },
        {
            "id": "Seberry",
            "type": "article",
            "title": "Hadamard matrices, sequences, and block designs.",
            "authors": "J. Seberry and M. Yamada",
            "year": "1992",
            "publisher": "John Wiley and Sons",
            "url": "http://mathscinet.ru/files/YamadaSeberry1992.pdf"
        },
        {
            "id": "Gaeta",
            "type": "article",
            "title": "Discrete phase-space approach to mutually orthogonal Latin squares",
            "authors": "M. Gaeta, O. Di Matteo, A. B. Klimov, and H. de Guise",
            "year": "2014",
            "journal": "J. Phys. A: Math. Theor.",
            "url": "https://arxiv.org/abs/1408.6742"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_haar_measure",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/simulating_vibronic_dynamics/metadata.json
{
  "title": "Simulating Vibronic Dynamics",
  "authors": [
    {
      "username": "emgem"
    }
  ],
  "executable_stable": true,
  "executable_latest": true,
  "dateOfPublication": "2026-06-10T00:00:00+00:00",
  "dateOfLastModification": "2026-06-10T00:00:00+00:00",
  "categories": ["Algorithms"],
  "tags": ["Vibronics", "Simulating", "Trotter", "Algorithm"],
  "previewImages": [
    {
      "type": "thumbnail",
      "uri": "/_static/demo_thumbnails/pennylane-demo-simulating-vibronic-dynamics-thumbnail.png"
    },
    {
      "type": "large_thumbnail",
      "uri": "/_static/demo_thumbnails/pennylane-demo-simulating-vibronic-dynamics-large-thumbnail.png"
    }
  ],
  "seoDescription": "A lot of interesting science occurs when systems become dynamic. Quantum computing shows promise to address the limitations faced by classical computers in dynamic simulations.",
  "doi": "",
  "references": [
     {
      "id": "Motlagh2025",
      "type": "article",
      "title": "Quantum Algorithms for Vibronic Dynamics: Case Study on Singlet Fission Solar Cell Design",
      "authors": "Motlagh, Lang, Jain, Aspuru-Guzik, and Arrazola",
      "year": "2025",
      "doi": "10.48550/arXiv.2411.13669",
      "url": "https://doi.org/10.48550/arXiv.2411.13669"
    },
    {
      "id": "Lang2026",
      "type": "article",
      "title": "Quantum Algorithm for Simulating Non-Adiabatic Dynamics at Metallic Surfaces",
      "authors": "Lang, Jain, Arrazola, and Motlagh",
      "year": "2026",
      "doi": "10.48550/arXiv.2601.16264",
      "url": "https://doi.org/10.48550/arXiv.2601.16264"
    }
  ],
  "basedOnPapers": [
    "10.48550/arXiv.2411.13669"
  ],
  "referencedByPapers": [],
  "relatedContent": [
    {
      "type":"demonstration",
      "id": "exploring_trotterization",
      "weight": 1.0
    },
    {
      "type":"demonstration",
      "id": "tutorial_resource_estimation_vibronic_dynamics",
      "weight": 1.0
    },
    {
      "type":"demonstration",
      "id": "tutorial_intro_qrom",
      "weight": 1.0
    }
  ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_achieving_universality_with_the_clifford_hierarchy/metadata.json
{
    "title": "Achieving universality with the Clifford hierarchy",
    "authors": [
        {
            "username": "dren"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2026-04-29T16:30:00+00:00",
    "dateOfLastModification": "2026-10-19T00:00:00+00:00",
    "categories": [
        "FTQC",
        "Quantum Computing"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/pennylane-demo-universality-and-clifford-hierarchy-thumbnail.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/pennylane-demo-universality-and-clifford-hierarchy-large-thumbnail.png"
        }
    ],
    "seoDescription": "Learn about a hidden mathematical structure connecting many quantum gates that enables universal and fault-tolerant quantum computing: the Clifford hierarchy",
    "doi": "",
    "references": [
        {
            "id": "anynonclifford",
            "type": "article",
            "title": "The invariants of the Clifford groups",
            "authors": "G. Nebe, E.M. Rains, N.J.A. Sloane",
            "year": "2000",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/math/0001038"
        },
        {
        "id": "universality",
        "type": "article",
        "title": "Universality in Quantum Computation",
        "authors": "D. Deutsch, A. Barenco, and A. Ekert",
        "year": "1995",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/quant-ph/9505018"
    },
    {
        "id": "qecbook",
        "type": "book",
        "title": "Surviving as a Quantum Computer in a Classical World",
        "authors": "D. Gottesman",
        "year": "2024",
        "journal": "arXiv",
        "url": "https://www.cs.umd.edu/~dgottesm/QECCbook-2024.pdf"
    },
    {
        "id": "SK_alg",
        "type": "article",
        "title": "The Solovay-Kitaev Algorithm",
        "authors": "C.M. Dawnson and M.A. Nielsen",
        "year": "2005",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/quant-ph/0505030"
    },
    {
        "id": "gridsynth",
        "type": "article",
        "title": "Optimal ancilla-free Clifford+T approximation of z-rotations",
        "authors": "N.J. Ross and P. Selinger",
        "year": "2016",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/1403.2975"
    },
    {
        "id": "gottesmanchuang",
        "type": "article",
        "title": "Quantum teleportation is a universal computational primitive",
        "authors": "D. Gottesman and I.L. Chuang",
        "year": "1999",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/quant-ph/9908010"
    },
    {
        "id": "onebit",
        "type": "article",
        "title": "Methodology for quantum logic gate construction",
        "authors": "X. Zhou, D.W. Leung, and I.L. Chuang",
        "year": "2000",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/quant-ph/0002039"
    },
    {
        "id": "semiclifford",
        "type": "article",
        "title": "Semi-Clifford operations, structure of :math:`C_k` hierarchy, and gate complexity for fault-tolerant quantum computation",
        "authors": "B. Zeng, X. Chen, and I.L. Chuang",
        "year": "2008",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/0712.2084"
    },
    {
        "id": "diagonal",
        "type": "article",
        "title": "Diagonal gates in the Clifford hierarchy",
        "authors": "S.X. Cui, D. Gottesman, and A. Krishna",
        "year": "2016",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/1608.06596"
    },
    {
        "id": "pauliframetracking",
        "type": "article",
        "title": "Fault-tolerant quantum computing in the Pauli or Clifford frame with slow error diagnostics",
        "authors": "C. Chamberland, P. Iyer, and D. Poulin",
        "year": "2017",
        "journal": "arXiv",
        "url": "https://arxiv.org/abs/1704.06662"
    },
        {
            "id": "climbdiagonal",
            "type": "article",
            "title": "Climbing the Diagonal Clifford Hierarchy",
            "authors": "J. Hu, Q. Liang, and R. Calderbank",
            "year": "2019",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/2110.11923"
        },
        {
            "id": "controlledgates",
            "type": "article",
            "title": "Controlled Gates in the Clifford Hierarchy",
            "authors": "J.T. Anderson and M. Weippert",
            "year": "2025",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/2410.04711"
        },
        {
            "id": "climb",
            "type": "article",
            "title": "Climbing the Clifford Hierarchy",
            "authors": "L. Bastioni, S. Glandon, T. Pllaha, M. Stewart, and P. Waitkevich",
            "year": "2026",
            "journal": "arXiv",
            "url": "https://arxiv.org/abs/2603.12088"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_teleportation",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_magic_states",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_magic_state_distillation",
            "weight": 0.5
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_How_to_simulate_quantum_circuits_with_tensor_networks/metadata.json
{
    "title": "How to simulate quantum circuits with tensor networks using DefaultTensor",
    "authors": [
        {
            "username": "Frisus95"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2024-07-09T00:00:00+00:00",
    "dateOfLastModification": "2026-04-14T15:48:14+00:00",
    "categories": [
        "Getting Started",
        "Quantum Computing",
        "Devices and Performance",
        "How-to"
    ],
    "tags": [
        "how to"
    ],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/thumbnail_how_to_default_tensor.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/thumbnail_large_how_to_default_tensor.png"
        }
    ],
    "seoDescription": "Learn how to simulate quantum circuits with tensor networks using the default.tensor PennyLane device.",
    "doi": "",
    "references": [
        {
            "id": "orus",
            "type": "article",
            "title": "A practical introduction to tensor networks: Matrix product states and projected entangled pair states",
            "authors": "R. Orús",
            "year": "2014",
            "journal": "Annals of Physics",
            "url": "https://www.sciencedirect.com/science/article/pii/S0003491614001596"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_tn_circuits",
            "weight": 1.0
        }
    ]
}

=== PennyLaneAI/demos/demonstrations_v2/tutorial_stabilizer_codes/metadata.json
{
    "title": "Stabilizer codes for quantum error correction",
    "authors": [
        {
            "username": "chsid"
        },
        {
            "username": "alvaro"
        }
    ],
    "executable_stable": true,
    "executable_latest": true,
    "dateOfPublication": "2025-08-19T09:00:00+00:00",
    "dateOfLastModification": "2026-07-14T15:00:00+00:00",
    "categories": [
        "Algorithms",
        "Quantum Computing",
        "Quantum Hardware"
    ],
    "tags": [],
    "previewImages": [
        {
            "type": "thumbnail",
            "uri": "/_static/demo_thumbnails/regular_demo_thumbnails/pennylane-demo-stabilizer-codes-thumbnail.png"
        },
        {
            "type": "large_thumbnail",
            "uri": "/_static/demo_thumbnails/large_demo_thumbnails/pennylane-demo-stabilizer-codes-large-thumbnail.png"
        }
    ],
    "seoDescription": "Learn all about the stabilizer formalism for quantum error correction with concrete coding examples.",
    "doi": "",
    "references": [
        {
            "id": "gottesman1997stabilizercodesquantumerror",
            "type": "phdthesis",
            "title": "Stabilizer Codes and Quantum Error Correction",
            "authors": "Daniel Gottesman",
            "year": "1997",
            "url": "https://arxiv.org/abs/quant-ph/9705052"
        }
    ],
    "basedOnPapers": [],
    "referencedByPapers": [],
    "relatedContent": [
        {
            "type": "demonstration",
            "id": "tutorial_game_of_surface_codes",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_toric_code",
            "weight": 1.0
        },
        {
            "type": "demonstration",
            "id": "tutorial_mbqc",
            "weight": 1.0
        }
    ]
}
